# -*- mode: ruby -*-
# vi: set ft=ruby :

#Определяем массив с настройкам ВМ (в данном примере одна ВМ)
lab01vm=[
    {
      :hostname => "kernelUpdate",
      :cpus => 2,
      :ram => 1024,
      :box => "generic/centos8s"
    }
]

#Настраиваем главную конфигурацию vagtant
Vagrant.configure("2") do |config|
  #Оключаем дефолтную шару
  config.vm.synced_folder ".", "/vagrant", disabled: true
  #Проходим по элементам массива lab01vm
  lab01vm.each do |vms|
    #Описываем конфигурацию машин
    config.vm.define vms[:hostname] do |node|
      #Развернуть машину из образа "generic/centos8s"
      node.vm.box = vms[:box]
      #Отключаем проверку обновлений образа
      node.vm.box_check_update = false
      #Задаем hostname машины
      node.vm.hostname = vms[:hostname]
      #Тонкие настройки для конкретной платформы виртуализации (провайдера)
      node.vm.provider "virtualbox" do |vb|
        #Отключаем GUI при старте ВМ
        vb.gui = false
        #Настраивае параметры cpu
        vb.cpus = vms[:cpus]
        #Настраиваем параметры ram
        vb.memory = vms[:ram]
        #Перезаписываем имя ВМ в Vbox
        vb.name = vms[:hostname]
      end
      #Описываем действия которые будут выполнены после старта ВМ
      node.vm.provision "shell" do |script|
        #script.inline = "echo Hello, World"
        script.path = "updateKernel.sh"
      end
    end
  end
end
